### ISSUE TITLE
redirect-to now returns HTTP-403

### ISSUE THREAD

**Issue by jonpryor** [mccutchen/go-httpbin#103]
Not sure if this is a deliberate or an accidental change, but starting around 2022-Nov-11, <https://httpbingo.org/redirect-to> started returning HTTP-403 errors instead of the expected HTTP-302:

```
% curl -D - 'https://httpbingo.org/redirect-to?url=https://example.com'
HTTP/2 403 
access-control-allow-credentials: true
access-control-allow-origin: *
content-type: text/plain; charset=utf-8
x-content-type-options: nosniff
date: Wed, 16 Nov 2022 15:56:03 GMT
content-length: 51
server: Fly/5f2bf728 (2022-11-11)
via: 2 fly.io
fly-request-id: 01GJ0JF2S5RG7Z8EV44KC0GJQ6-iad

Forbidden redirect URL. Be careful with this link.
```

Compare to <https://httpbin.org>:

```
% curl -D - 'https://httpbin.org/redirect-to?url=https://example.com'
HTTP/2 302 
date: Wed, 16 Nov 2022 15:56:39 GMT
content-type: text/html; charset=utf-8
content-length: 0
location: http://example.com
server: gunicorn/19.9.0
access-control-allow-origin: *
access-control-allow-credentials: true

```

**Comment by jonpryor** [comment]
Looks like this was a deliberate change as part of #97.

**Comment by mccutchen** [comment]
Yep, and I’m sorry for the disruption!

Note that this restriction is only applied to the public httpbingo.org instance I operate, mostly because that instance has seen a whole lot of usage of `/redirect-to` with spammy/scammy/malicious URLs. 

Do you have a particular use-case or need for specific (legitimate) redirect destinations?

**Comment by mccutchen** [comment]
Just deployed [an update that now allows `example.{com,net,org}`](https://github.com/mccutchen/httpbingo.org/commit/977d96825fb26e0eb48a9ce5c1d2ce8e7c971598), so at least your example curl request should work.

I'm going to take a quick pass at making that error message a little more helpful, so that it's clear what domains it _will_ allow when the restriction is in place.

**Comment by jonpryor** [comment]
@mccutchen [asked](https://github.com/mccutchen/go-httpbin/issues/103#issuecomment-1317393698):

> Do you have a particular use-case or need for specific (legitimate) redirect destinations?

We were using <https://httpbingo.org> as part of our [unit tests](https://github.com/xamarin/xamarin-android/blob/0ee174c9407068c046dc7c5995576f3d4c5b74da%5E/tests/Mono.Android-Tests/Xamarin.Android.Net/AndroidClientHandlerTests.cs#L249), and they started failing this week… :-)

We updated our tests to instead use <https://httpbin.org>, and "publicly using your server for our unit tests" is *probably* not expected/anticipated behavior, but that was our use case.

**Comment by mccutchen** [comment]
Gotcha! Again, I’m sorry for the unexpected breakage, and I’d be happy to add accommodate additional “safe” redirect destinations if it would help.

**Comment by mccutchen** [comment]
Closing for now, as this was an intentional — if unfortunately disruptive — change for security reasons.
