### ISSUE TITLE
When using a "prefix", respond to requests that don't have a trailing slash

### ISSUE THREAD

**Issue by joshuawhite929** [mccutchen/go-httpbin#170]
Given the prefix "/foo", httpbin will render its default page only at "/foo/" and not just "/foo".

**Comment by mccutchen** [comment]
Thanks for the report @joshuawhite929.  I poked at this a bit, and because the entire implementation of go-httpbin's prefix support basically boils down to a use of the stdlib's http.StripPrefix middleware …

https://github.com/mccutchen/go-httpbin/blob/8f905de9567b18185492ac6af36156a439d980a9/httpbin/httpbin.go#L207-L209

… I don't think it's worth the effort to re-implement the same functionality in a way that handles this edge case.

I'm going to close this for now, but if someone is inclined to do a simple replacement implementation, I'll take a look at it!
