### ISSUE TITLE
/drip endpoint seems broken?

### ISSUE THREAD

**Issue by StefanKarpinski** [mccutchen/go-httpbin#40]
Finding this project very useful! Super easy to deploy and use for CI. One endpoint that seems to be broken is the `/drip` endpoint. When I fetch it with libcurl, the progress callback shows that I only get one response packet. By comparison, when I use `https://httpbin.org/drip` I get ten packets of a byte each.

**Comment by mccutchen** [comment]
Hi, thanks for the report!  To clarify, are you testing against https://httpbingo.org or against an instance of go-httpbin running locally?

I did a little digging, and it turns out that this is definitely broken on https://httpbingo.org, because Google App Engine (where it's currently deployed) [explicitly disallows streaming responses](https://cloud.google.com/appengine/docs/standard/go/how-requests-are-handled):

> App Engine does not support streaming responses where data is sent in incremental chunks to the client while a request is being processed. All data from your code is collected as described above and sent as a single HTTP response.

That's a real shame, and breaks a few of the current endpoints in the same way.  I guess I've got to find another place to host this little thing!

The good news is that, as far as I can tell, the `/drip` endpoint should work with a local instance of go-httpbin, but I'd love to know if that's not what you're seeing.  If this is not working as expected against a local instance, can you provide a quick way to reproduce?

The [tests for this endpoint](https://github.com/mccutchen/go-httpbin/blob/40a126261600a23a71417529cef4c2d43631ee82/httpbin/handlers_test.go#L1545-L1565) are a little weird to write (IIRC the golang standard library http client makes it hard to directly test because it "helpfully" handles the chunked transfer encoding before it gets to my code).

The curl command line client seems to get a streaming response locally, as shown here (note the `--no-buffer` flag to prevent curl from buffering the whole response):

```
curl -v --no-buffer 'http://localhost:8080/drip?duration=10&numbytes=10'
```

![Untitled2](https://user-images.githubusercontent.com/57938/94493490-c4aaba00-01ba-11eb-84ec-f2c6b6b2e17c.gif)

**Comment by mccutchen** [comment]
(Opened #41 to track the task of finding a new home for httpbingo.org)

**Comment by StefanKarpinski** [comment]
I had tried both https://httpbingo.org and https://httpbingo.julialang.org, which @staticfloat just setup for the Julia project so we don't tax your servers with our CI and so that we're more insulated from network issues. Both had the issue but it may be the same problem. @staticfloat, do you think it's the same issue for our setup?

**Comment by mccutchen** [comment]
@StefanKarpinski as of https://github.com/mccutchen/go-httpbin/pull/42, the https://httpbingo.org/drip endpoint should be working again (pending DNS propagation).  Please let me know if it's working for you!

**Comment by StefanKarpinski** [comment]
Ok, this works for me with those parameters, yay! However, the defaults seem to differ from what's documented on https://httpbin.org (there are no defaults shown on https://httpbingo.org):

- duration = 2
- numbytes = 10
- code = 200
- delay = 2

Would it make sense to match the defaults from httpbin?

**Comment by StefanKarpinski** [comment]
Technically unrelated, but it seems that httpbingo does not send a content-length (this happens to make my tests fail), whereas httpbin does send a content length, allowing proper progress estimation.

**Comment by mccutchen** [comment]
Well, this quest for httpbin compatibility is becoming kind of funny.

As of https://github.com/mccutchen/go-httpbin/pull/43 I think I've addressed the incompatibilities mentioned above (thanks again for the detailed report) but, unfortunately, setting the `Content-Length` header seems to cause the Google-managed load balancer serving httpbingo.org back into a mode where it no longer streams responses.

I do agree that it makes sense for `/drip` to return the expected content length, now I've just got to find another place to deploy this thing that won't get in the way.

**Comment by staticfloat** [comment]
FWIW, we're deploying our instance on AWS Lightsail [via docker with watchtower and certbot auto-integrated](https://github.com/staticfloat/httpbingo.julialang.org), which is quite cheap for the bandwidth it affords ($5/month for 2 TB/month), although we don't use a load balancer.

**Comment by StefanKarpinski** [comment]
Funny how "helpful" these services can be, right? 😬

**Comment by StefanKarpinski** [comment]
Thank you!

**Comment by mccutchen** [comment]
One last update, for now:  As of #45, https://httpbingo.org/drip should be working as expected.
