### ISSUE TITLE
[Feature request] Add prometheus or metrics api 

### ISSUE THREAD

**Issue by Lynskylate** [mccutchen/go-httpbin#74]

**Comment by mccutchen** [comment]
Right now, this project does not have any dependencies outside the stdlib. I'm extremely reluctant to add any, in order to ensure that it continues to be as easy/safe as possible for other apps to include it in their testing dependencies without having to pull in a lot of additional 3rd party code.

That being said, it should be relatively easy to wrap this package and use the `Observer` hooks added in https://github.com/mccutchen/go-httpbin/pull/11 to add whatever extra instrumentation you need, though this does require building/deploying your own version.

Take a look at [examples/custom-instrumentation](https://github.com/mccutchen/go-httpbin/tree/main/examples/custom-instrumentation) to see what this might look like. (I just added this in https://github.com/mccutchen/go-httpbin/pull/75, because you reminded me that this was never actually documented!)
